version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER:  shortener
      POSTGRES_PASSWORD: password123
      POSTGRES_DB:     shortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_DSN:       postgres://shortener:password123@db:5432/shortener?sslmode=disable
      REDIS_ENDPOINT:     redis:6379
      SONYFLAKE_MACHINE_ID: "1"
    ports:
      - "50051:50051"
      - "9090:9090"
volumes:
  pgdata:
