global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "url-shortener"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:9090"]