global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: "url-shortener"
    metrics_path: /metrics
    scrape_interval: 5s
    scheme: https
    static_configs:
      - targets: ["url-shortener-production-ba38.up.railway.app"]